/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSort */

#ifndef _Included_InsertionSort
#define _Included_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InsertionSort
 * Method:    binarySort
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_InsertionSort_binarySort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
