/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSorter */

#ifndef _Included_InsertionSorter
#define _Included_InsertionSorter
#ifdef __cplusplus
extern "C" {
#endif
#undef InsertionSorter_MIN_PRIORITY
#define InsertionSorter_MIN_PRIORITY 1L
#undef InsertionSorter_NORM_PRIORITY
#define InsertionSorter_NORM_PRIORITY 5L
#undef InsertionSorter_MAX_PRIORITY
#define InsertionSorter_MAX_PRIORITY 10L
/*
 * Class:     InsertionSorter
 * Method:    binarySort
 * Signature: ([ID)I
 */
JNIEXPORT jint JNICALL Java_InsertionSorter_binarySort
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
